export const GIFTS_API_REQUEST = 'GIFTS_API_REQUEST';
export const GIFTS_API_START = 'GIFTS_API_START';
export const GIFTS_API_RESULT = 'GIFTS_API_RESULT';

export const PRODUCTS_API_REQUEST = 'PRODUCTS_API_REQUEST';
export const PRODUCTS_API_START = 'PRODUCTS_API_START';
export const PRODUCTS_API_RESULT = 'PRODUCTS_API_RESULT';

export const APPOINTMENTS_API_REQUEST = 'APPOINTMENTS_API_REQUEST';
export const APPOINTMENTS_API_START = 'APPOINTMENTS_API_START';
export const APPOINTMENTS_API_RESULT = 'APPOINTMENTS_API_RESULT';

export const SHOW_INFOWINDOW = 'SHOW_INFOWINDOW';
export const UPDATE_LIST = 'UPDATE_LIST;';
export const MAP_LOADED = 'MAP_LOADED';

export const SET_BROWSER_LOCATION = 'SET_BROWSER_LOCATION';

//Global
export const INIT = 'INIT';

//Reset
export const RESET = 'RESET';
export const RESET_FORMS = 'RESET_FORMS';
export const RESET_UPLOAD = 'RESET_UPLOAD';
export const RESET_APP = 'RESET_APP';

//Sagas
export const AUTH_SAGA = 'AUTH_SAGA';
export const PRODUCS_SAGA = 'PRODUCS_SAGA';
export const USERS_SAGA = 'USERS_SAGA';
export const GIFTS_SAGA = 'GIFTS_SAGA';
export const APPOINTMENTS_SAGA = 'APPOINTMENTS_SAGA';
export const SERVICES_SAGA = 'SERVICES_SAGA';

//Update Single Aspect
export const UPDATE_APP_ASPECT = 'UPDATE_APP_ASPECT';
export const UPDATE_APPOINTMENTS_ASPECT = 'UPDATE_APPOINTMENTS_ASPECT';
export const UPDATE_FORMS_ASPECT = 'UPDATE_FORMS_ASPECT';
export const UPDATE_SESSION_ASPECT = 'UPDATE_SESSION_ASPECT';
export const UPDATE_UPLOAD_ASPECT = 'UPDATE_UPLOAD_ASPECT';
export const UPDATE_USERS_ASPECT = 'UPDATE_USERS_ASPECT';
export const UPDATE_SERVICES_ASPECT = 'UPDATE_SERVICES_ASPECT';
export const UPDATE_PERKS_ASPECT = 'UPDATE_PERKS_ASPECT';
export const UPDATE_GIFTS_ASPECT = 'UPDATE_GIFTS_ASPECT';


//Update Reducer
export const UPDATE_APP_REDUCER = 'UPDATE_APP_REDUCER';
export const UPDATE_APPOINTMENTS_REDUCER = 'UPDATE_APPOINTMENTS_REDUCER';
export const UPDATE_FORMS_REDUCER = 'UPDATE_FORMS_REDUCER';
export const UPDATE_SESSION_REDUCER = 'UPDATE_SESSION_REDUCER';
export const UPDATE_UPLOAD_REDUCER = 'UPDATE_UPLOAD_REDUCER';
export const UPDATE_USERS_REDUCER = 'UPDATE_USERS_REDUCER';
export const UPDATE_GIFTS_REDUCER = 'UPDATE_GIFTS_REDUCER';
export const UPDATE_SERVICES_REDUCER = 'UPDATE_SERVICES_REDUCER';
export const UPDATE_PERKS_REDUCER = 'UPDATE_PERKS_REDUCER';

//CREATE Reducer
export const CREATE_APP_REDUCER = 'CREATE_APP_REDUCER';
export const CREATE_APPOINTMENTS_REDUCER = 'CREATE_APPOINTMENTS_REDUCER';
export const CREATE_FORMS_REDUCER = 'CREATE_FORMS_REDUCER';
export const CREATE_SESSION_REDUCER = 'CREATE_SESSION_REDUCER';
export const CREATE_UPLOAD_REDUCER = 'CREATE_UPLOAD_REDUCER';
export const CREATE_USERS_REDUCER = 'CREATE_USERS_REDUCER';
export const CREATE_GIFTS_REDUCER = 'CREATE_GIFTS_REDUCER';
export const CREATE_SERVICES_REDUCER = 'CREATE_SERVICES_REDUCER';
export const CREATE_PERKS_REDUCER = 'CREATE_PERKS_REDUCER';

//SPECIFIC

//SESSION
export const AUTH_USER_SET = 'AUTH_USER_SET';
export const LOG_OUT = 'LOG_OUT';
export const SIGN_IN_FACEBOOK = 'SIGN_IN_FACEBOOK';
export const SIGN_IN_GOOGLE = 'SIGN_IN_GOOGLE';
export const SIGN_IN_PHONE = 'SIGN_IN_PHONE';
export const GET_PHONE_CONFIRMATION = 'GET_PHONE_CONFIRMATION';
export const VERIFY_SMS = 'VERIFY_SMS';
export const ROUTE_LOADING = 'ROUTE_LOADING';

//APPOINTMENTS
export const UPDATE_FETCHED_APPOINTMENTS = 'UPDATE_FETCHED_APPOINTMENTS';
export const UPDATE_FETCHED_GIFTS = 'UPDATE_FETCHED_GIFTS';
export const UPDATE_MY_APPOINTMENTS = 'UPDATE_MY_APPOINTMENTS';

//USERS
export const UPDATE_CART = 'UPDATE_CART';
